const ITEMS=[
{skill:'hash',title:'Two Sum ordering',prompt:'Which line belongs at ??? so one element cannot match itself?',code:`seen = set()\nfor x in nums:\n    need = target - x\n    ???\n    seen.add(x)`,choices:[[`if need in seen: return True`,1,'Check before inserting x; otherwise x could match itself when target == 2*x.'],[`seen.add(need)`,0,'You want to remember values actually encountered, not the complement you hope to see.'],[`if x in seen: return True`,0,'That detects duplicates, not a pair summing to target.']],takeaway:'When the current item is not allowed to pair with itself, lookup often happens before insertion.',lesson:'hash',lc:['Two Sum','https://leetcode.com/problems/two-sum/']},
{skill:'graphs',title:'BFS visited timing',prompt:'Where should seen.add(v) go?',code:`q = deque([start])\nseen = {start}\nwhile q:\n    u = q.popleft()\n    for v in graph[u]:\n        if v not in seen:\n            ???\n            q.append(v)`,choices:[[`seen.add(v)`,1,'Mark on enqueue so another parent cannot enqueue the same node before it is processed.'],[`# do nothing; mark after popleft`,0,'Waiting until dequeue permits duplicate queue entries.'],[`seen.remove(v)`,0,'That does the opposite of preventing revisits.']],takeaway:'BFS nodes become discovered when enqueued, not when eventually popped.',lesson:'graphs',lc:['Shortest Path in Binary Matrix','https://leetcode.com/problems/shortest-path-in-binary-matrix/']},
{skill:'union',title:'Union-Find path compression',prompt:'What should ??? do?',code:`def find(x):\n    if parent[x] != x:\n        ???\n    return parent[x]`,choices:[[`parent[x] = find(parent[x])`,1,'This recursively finds the root and rewires x directly toward it.'],[`parent[x] = x`,0,'That would split x from its real component.'],[`return parent[parent[x]]`,0,'Jumping two levels once does not necessarily reach the root or compress the full path.']],takeaway:'Path compression is just “find the root, then remember it directly.”',lesson:'union',lc:['Accounts Merge','https://leetcode.com/problems/accounts-merge/']},
{skill:'heap',title:'Top-K eviction',prompt:'Which operation belongs at ??? when keeping the K largest scores?',code:`heap = []\nfor score in scores:\n    heapq.heappush(heap, score)\n    if len(heap) > k:\n        ???`,choices:[[`heapq.heappop(heap)`,1,'In a min-heap of winners, the root is the weakest winner.'],[`heap.pop()`,0,'The last array element is not guaranteed to be the smallest heap item.'],[`heapq.nlargest(k, heap)`,0,'That repeatedly recomputes selection instead of maintaining the heap.']],takeaway:'For K largest, a size-K min-heap makes the current cutoff cheap to evict.',lesson:'heap',lc:['Top K Frequent Elements','https://leetcode.com/problems/top-k-frequent-elements/']},
{skill:'topo',title:'Topological queue rule',prompt:'When should dependent v enter the queue?',code:`u = q.popleft()\nfor v in graph[u]:\n    indegree[v] -= 1\n    ???`,choices:[[`if indegree[v] == 0: q.append(v)`,1,'Only zero unmet prerequisites means v is legal now.'],[`if indegree[v] > 0: q.append(v)`,0,'That queues a task while it still has unmet prerequisites.'],[`q.append(v)`,0,'Unconditional enqueue can violate the dependency order and duplicate work.']],takeaway:'Kahn’s algorithm queue means “legal right now,” not merely “discovered.”',lesson:'topo',lc:['Course Schedule II','https://leetcode.com/problems/course-schedule-ii/']},
{skill:'window',title:'Sliding-window repair',prompt:'What loop restores the uniqueness invariant?',code:`for right, x in enumerate(items):\n    while ???:\n        seen.remove(items[left])\n        left += 1\n    seen.add(x)`,choices:[[`x in seen`,1,'Keep shrinking until the incoming x no longer duplicates anything in the window.'],[`x not in seen`,0,'That would shrink valid windows and stop on invalid ones.'],[`left < right`,0,'Window size is not the validity rule.']],takeaway:'A sliding-window while-loop should state the exact condition that makes the current window invalid.',lesson:'window',lc:['Longest Substring Without Repeating Characters','https://leetcode.com/problems/longest-substring-without-repeating-characters/']},
{skill:'prefix',title:'Prefix-map initialization',prompt:'Why is freq initialized this way?',code:`freq = {0: 1}\nprefix = 0\nanswer = 0\nfor x in nums:\n    prefix += x\n    answer += freq.get(prefix-k, 0)\n    freq[prefix] = freq.get(prefix, 0) + 1`,choices:[[`It represents one empty prefix before the array starts`,1,'That lets a subarray beginning at index 0 be counted when prefix == k.'],[`It avoids division by zero`,0,'There is no division here.'],[`It means the first input value is zero`,0,'The map describes prefix sums seen, not input values.']],takeaway:'The empty prefix is a real boundary case and often appears as an initial zero entry.',lesson:'prefix',lc:['Subarray Sum Equals K','https://leetcode.com/problems/subarray-sum-equals-k/']},
{skill:'prefix',title:'Prefix-map operation order',prompt:'Which ordering is correct?',code:`prefix += x\n# A and B must happen in the right order\nA: answer += freq.get(prefix-k, 0)\nB: freq[prefix] = freq.get(prefix, 0) + 1`,choices:[[`A then B`,1,'Query earlier prefixes before registering the current prefix as an “earlier” one.'],[`B then A`,0,'That can incorrectly let the current prefix participate in its own lookup, especially when k == 0.'],[`Order never matters`,0,'The map’s meaning is “prefixes strictly before the current position.”']],takeaway:'Be explicit about what the dictionary represents before and after each line.',lesson:'prefix',lc:['Subarray Sum Equals K','https://leetcode.com/problems/subarray-sum-equals-k/']},
{skill:'binary',title:'Binary-search boundary',prompt:'You seek the smallest feasible x. If feasible(mid) is true, which update preserves mid as a candidate?',code:`while lo < hi:\n    mid = (lo + hi) // 2\n    if feasible(mid):\n        ???\n    else:\n        lo = mid + 1`,choices:[[`hi = mid`,1,'mid works and may be the first working value, so keep it in the search interval.'],[`hi = mid - 1`,0,'That can discard the correct answer when mid is exactly the first feasible value.'],[`lo = mid + 1`,0,'That searches to the right even though you want the smallest feasible value.']],takeaway:'Binary-search updates follow from one question: can mid itself still be the answer?',lesson:'binary',lc:['Koko Eating Bananas','https://leetcode.com/problems/koko-eating-bananas/']},
{skill:'dijkstra',title:'Dijkstra stale entries',prompt:'What guard belongs immediately after heappop?',code:`d, u = heapq.heappop(pq)\n???\nfor v, w in graph[u]:\n    nd = d + w\n    if nd < dist[v]:\n        dist[v] = nd\n        heapq.heappush(pq, (nd, v))`,choices:[[`if d != dist[u]: continue`,1,'An older, worse heap entry may remain after a better distance was pushed.'],[`if d == dist[u]: continue`,0,'That skips the current best entry instead of stale ones.'],[`dist[u] = float('inf')`,0,'That destroys the best-known distance.']],takeaway:'Python Dijkstra usually tolerates duplicate heap entries and cheaply ignores stale ones.',lesson:'dijkstra',lc:['Network Delay Time','https://leetcode.com/problems/network-delay-time/']},
{skill:'trees',title:'Recursive base case',prompt:'What is the natural base case for computing tree height?',code:`def height(node):\n    if node is None:\n        ???\n    return 1 + max(height(node.left), height(node.right))`,choices:[[`return 0`,1,'An empty subtree contributes zero height under this convention.'],[`return 1`,0,'Then every leaf would become height 2 with this recurrence.'],[`raise Exception()`,0,'Null children are expected structure, not errors.']],takeaway:'Choose a base case that makes the recurrence work cleanly at leaves.',lesson:'trees',lc:['Maximum Depth of Binary Tree','https://leetcode.com/problems/maximum-depth-of-binary-tree/']},
{skill:'dp',title:'Memoization trigger',prompt:'Which single Python addition prevents repeated solution of the same remaining amount?',code:`from functools import cache\n\n???\ndef solve(remaining):\n    if remaining == 0: return 0\n    ...`,choices:[[`@cache`,1,'The function result is memoized by its arguments.'],[`@staticmethod`,0,'That changes method binding, not repeated computation.'],[`@property`,0,'That exposes a method as an attribute and is unrelated to DP caching.']],takeaway:'For interview DP, top-down recursion plus memoization is often the fastest path from recurrence to working code.',lesson:'dp',lc:['Coin Change','https://leetcode.com/problems/coin-change/']]}
];
const KEY='amazon-skill-stats';let stats=JSON.parse(localStorage.getItem(KEY)||'{}');let order=[],i=0,correct=0,answered=0,locked=false,weakFirst=false;const $=x=>document.getElementById(x);
function esc(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function shuffle(a){a=[...a];for(let n=a.length-1;n>0;n--){const j=Math.floor(Math.random()*(n+1));[a[n],a[j]]=[a[j],a[n]]}return a}
function acc(skill){const s=stats[skill];return !s||!s.attempts?null:s.correct/s.attempts}
function record(skill,ok){const s=stats[skill]||(stats[skill]={attempts:0,correct:0});s.attempts++;if(ok)s.correct++;localStorage.setItem(KEY,JSON.stringify(stats))}
function makeOrder(){if(!weakFirst)return shuffle(ITEMS);return [...ITEMS].sort((a,b)=>{const aa=acc(a.skill),bb=acc(b.skill);return (aa===null ? .55 : aa)-(bb===null ? .55 : bb)})}
function start(){order=makeOrder();i=0;correct=0;answered=0;render()}
function update(){$('progress').textContent=order.length?`${Math.min(i+1,order.length)}/${order.length}`:'0/0'}
function render(){if(i>=order.length){$('trainer').innerHTML=`<div class="endCard"><h2>Finished · ${correct}/${answered}</h2><p>Run it again later. The point is to make these dangerous one-line decisions automatic.</p><button class="btn primary" id="again">Shuffle again</button></div>`;$('again').onclick=start;$('progress').textContent=`${order.length}/${order.length}`;return}locked=false;const q=order[i];$('trainer').innerHTML=`<article class="questionCard"><div class="qTop"><span class="qNum">Reflex ${i+1} of ${order.length}</span><span class="patternReveal">${esc(q.title)}</span></div><h2>${esc(q.prompt)}</h2><div class="codeBlock"><pre>${esc(q.code)}</pre></div><div id="choices">${q.choices.map((c,j)=>`<button class="choice" data-i="${j}">${esc(c[0])}</button>`).join('')}</div><div id="feedback" class="stageFeedback"></div><div id="after"></div></article>`;document.querySelectorAll('#choices .choice').forEach(b=>b.onclick=()=>answer(+b.dataset.i));update()}
function answer(j){if(locked)return;locked=true;const q=order[i],c=q.choices[j],ok=c[1]===1;answered++;if(ok)correct++;record(q.skill,ok);const bs=[...document.querySelectorAll('#choices .choice')];bs.forEach((b,k)=>{b.disabled=true;if(q.choices[k][1]===1)b.classList.add('correct')});bs[j].classList.add(ok?'correct':'wrong');$('feedback').innerHTML=`<b>${ok?'Yes.':'Not quite.'}</b> ${esc(c[2])}`;$('after').innerHTML=`<div class="whyBox"><b>Reflex to keep:</b> ${esc(q.takeaway)}<div class="actions"><a class="btn small" href="index.html?review=${q.lesson}">Review lesson</a><a class="btn small" target="_blank" href="${q.lc[1]}">${esc(q.lc[0])}</a><button class="btn primary" id="next">Next</button></div></div>`;$('next').onclick=()=>{i++;render()}}
$('start').onclick=()=>{weakFirst=false;start()};$('weak').onclick=()=>{weakFirst=true;start()};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});