Q.push(
{id:'pair-indices',skill:'hash',scenario:'You have an unsorted list of product prices and must return the indices of two different prices whose sum is a target.',steps:[
{p:'What should the dictionary map?',c:[['Earlier price → its index',1,'You need fast complement lookup and must return positions.'],['Index → target',0,'That does not answer whether the needed price has appeared.'],['Running sum → index',0,'The pair condition is about individual complementary values.']]},
{p:'For current value x, what key do you look up?',c:[['target - x',1,'That is the only earlier value that can complete the pair.'],['target + x',0,'That would overshoot the target.'],['x / target',0,'The relation is additive, not multiplicative.']]},
{p:'Why process lookup before storing the current index?',c:[['To avoid matching the same element with itself',1,'The current position is not an earlier, distinct element yet.'],['Because dictionaries require sorted inserts',0,'They do not.'],['To save memory',0,'The memory use is unchanged.']]}],h:['Turn x + y = target into y = target - x.','Because indices are required, store more than a set: value → index.'],model:'“I scan once with a dictionary from value to earlier index. For x at index i, I check target-x first; if present I return those two indices, otherwise I store x→i. Expected O(n) time and O(n) space.”',links:[['Two Sum','https://leetcode.com/problems/two-sum/']]},
{id:'components',skill:'graphs',scenario:'A catalog relationship graph may be disconnected. Count how many separate connected groups of products it contains.',steps:[
{p:'What is the repeated operation?',c:[['Start a traversal from each node not yet visited',1,'Each new traversal consumes exactly one previously unseen connected component.'],['Run shortest path between every pair',0,'Distances are irrelevant and that is vastly more work.'],['Sort node IDs',0,'ID order does not reveal connectivity.']]},
{p:'Breadth-first or depth-first search?',c:[['Either works',1,'You only need to mark everything reachable, not optimize a path length.'],['Only breadth-first search',0,'Layer order is unnecessary for component counting.'],['Only depth-first search',0,'Breadth-first works just as well.']]},
{p:'What is the answer increment tied to?',c:[['Beginning a traversal from an unseen node',1,'That unseen start represents a new component.'],['Every edge followed',0,'A component can contain many edges.'],['Every leaf reached',0,'Graphs do not even require a tree-like leaf concept.']]}],h:['Think “paint everything reachable from one seed.”','Every time you need a new seed, you found another component.'],model:'“I keep one global seen set. For each node, if it is unseen I increment the component count and run BFS or DFS to mark its whole component. Each node and edge is processed only a constant number of times.”',links:[['Number of Provinces','https://leetcode.com/problems/number-of-provinces/'],['Number of Islands','https://leetcode.com/problems/number-of-islands/']]},
{id:'redundant-edge',skill:'union',scenario:'Edges are added to an initially disconnected undirected graph. Find the first edge that connects two nodes already in the same component.',steps:[
{p:'What does an edge whose endpoints already have the same representative imply?',c:[['It would create a cycle / redundant connection',1,'They are already connected by some existing path.'],['It joins two new components',0,'Same representative means there are not two components.'],['It should reset the component',0,'No reset is needed.']]},
{p:'What do you do for a non-redundant edge?',c:[['Union the two components',1,'Future connectivity queries should reflect the new edge.'],['Push it into a min-heap',0,'There is no priority ordering here.'],['Run binary search',0,'There is no monotonic numeric boundary.']]},
{p:'Why is this preferable to running a full graph traversal before every edge?',c:[['Union-Find maintains connectivity incrementally',1,'Repeated connectivity queries become extremely cheap.'],['Union-Find sorts edges automatically',0,'It does not.'],['Traversals cannot detect connectivity',0,'They can; they are just more expensive when repeated after every update.']]}],h:['Ask whether u and v were already connected before adding (u,v).','find(u) == find(v) is the key test.'],model:'“For each edge (u,v), I compare their Union-Find representatives. If they match, this edge is redundant; otherwise I union the components. That avoids a fresh traversal after every insertion.”',links:[['Redundant Connection','https://leetcode.com/problems/redundant-connection/']]},
{id:'kclosest',skill:'heap',scenario:'A stream of embeddings arrives with a distance to a query. Return only the K closest items; n is huge and K is small.',steps:[
{p:'Compared with the “K largest scores” example, what changes conceptually?',c:[['You still keep only K current winners, but the eviction boundary represents the worst distance',1,'The invariant is the same: preserve K best seen so far.'],['You must sort all n items',0,'K is still tiny relative to n.'],['A heap can only solve largest-K problems',0,'Heap orientation/key choice handles either direction.']]},
{p:'What invariant matters?',c:[['The heap contains the K closest candidates seen so far',1,'That is the useful statement independent of implementation details.'],['The heap contains every candidate',0,'That defeats the space goal.'],['The heap is globally sorted',0,'A heap guarantees only its heap property, not total ordering.']]},
{p:'What should you be able to explain before code?',c:[['Which current winner is easiest to evict and why',1,'Heap orientation follows directly from that choice.'],['The exact internal array shape after every push',0,'That is library implementation detail.'],['Why all distances are unique',0,'They need not be.']]}],h:['The heap should make the weakest current winner easy to remove.','For closest-K, think “which of my K winners is farthest?”'],model:'“I keep K winners and arrange the heap/key so the farthest current winner is the eviction boundary. Each candidate only needs to compete with that boundary, giving O(n log K) rather than sorting all n.”',links:[['K Closest Points to Origin','https://leetcode.com/problems/k-closest-points-to-origin/']]},
{id:'build-order',skill:'topo',scenario:'Several model artifacts depend on other artifacts. You need any valid build order; more than one order may be correct.',steps:[
{p:'Does having multiple zero-prerequisite choices mean failure?',c:[['No; it means multiple valid orders may exist',1,'Any currently legal node can be chosen.'],['Yes; topological order must be unique',0,'Uniqueness is not required unless explicitly asked.'],['Yes; the graph must be a tree',0,'Dependency graphs can branch and merge.']]},
{p:'Which graph direction makes indegree intuitive?',c:[['prerequisite → dependent',1,'Then indegree counts how many prerequisites remain.'],['dependent → prerequisite only',0,'You could design a variant, but it no longer matches the standard indegree interpretation.'],['Direction is meaningless',0,'Topological ordering is specifically about directed constraints.']]},
{p:'What does a self-dependency imply?',c:[['A cycle, so no valid full order',1,'The node can never reach zero unmet prerequisites.'],['A harmless duplicate',0,'It blocks its own prerequisite count.'],['A disconnected component',0,'Self-cycle and disconnection are different.']]}],h:['Topological sort is about partial order, not necessarily one exact sequence.','Indegree should mean “how many things must happen before me?”'],model:'“I represent prerequisite→dependent edges and indegrees. Any zero-indegree artifact is legal, so multiple choices are fine. Processing all nodes gives a valid order; any cyclic remainder makes a full order impossible.”',links:[['Course Schedule II','https://leetcode.com/problems/course-schedule-ii/']]},
{id:'positive-window',skill:'window',scenario:'All values are positive. Find the shortest contiguous subarray whose sum is at least target.',steps:[
{p:'Why does sliding window work particularly well with positive values?',c:[['Expanding right can only increase the sum; shrinking left can only decrease it',1,'That monotonic behavior tells you which boundary to move.'],['Positive arrays are automatically sorted',0,'They are not.'],['Hash maps cannot store positive numbers',0,'They can.']]},
{p:'When the window sum is already at least target, what should you try?',c:[['Shrink from the left while staying valid',1,'You are minimizing length, so discard unnecessary prefix items.'],['Keep expanding forever',0,'That cannot improve a minimum length while already valid.'],['Restart at the right boundary',0,'That discards useful overlapping candidates.']]},
{p:'What changes if arbitrary negative values are allowed?',c:[['This simple monotonic window logic may fail',1,'Removing a negative can increase the sum; direction is no longer predictable.'],['Nothing at all',0,'The positivity assumption is what makes the boundary movement safe.'],['The answer can only get longer',0,'No such rule holds.']]}],h:['Ask how the sum changes when either boundary moves.','With all-positive values, boundary moves have predictable direction.'],model:'“Because all values are positive, I expand right until the sum is sufficient, then shrink left as much as possible while recording the best length. Each boundary only moves forward, so the scan is O(n).”',links:[['Minimum Size Subarray Sum','https://leetcode.com/problems/minimum-size-subarray-sum/']]},
{id:'balanced-binary',skill:'prefix',scenario:'In a binary array, find the longest contiguous range containing the same number of 0s and 1s.',steps:[
{p:'What transformation makes this a prefix-sum equality problem?',c:[['Treat 0 as -1 and 1 as +1',1,'A balanced range then has net sum zero.'],['Treat both 0 and 1 as +1',0,'That only measures length.'],['Sort all values first',0,'Sorting destroys contiguity.']]},
{p:'What does seeing the same prefix sum at positions i and j tell you?',c:[['The range between them has net sum zero',1,'Equal cumulative totals cancel when subtracted.'],['Every element between them is zero',0,'Only the net transformed sum is zero.'],['The range is sorted',0,'Prefix sums say nothing about ordering.']]},
{p:'For longest length, what should the map store for each prefix sum?',c:[['Its earliest index',1,'The earliest occurrence gives the longest later span with the same prefix.'],['Its latest index only',0,'Overwriting the earliest loses longer candidates.'],['A heap of all indices',0,'You only need the earliest.']]}],h:['Convert “equal counts” into “difference equals zero.”','If two cumulative differences are equal, the interval between them changes the difference by zero.'],model:'“I map 0→-1 and 1→+1, then track a running prefix. When a prefix repeats, the interval since its first occurrence is balanced. I preserve the earliest index for each prefix to maximize length.”',links:[['Contiguous Array','https://leetcode.com/problems/contiguous-array/']]},
{id:'rate-search',skill:'binary',scenario:'A worker can process r records per hour. Find the minimum integer r that finishes a set of batches within H hours.',steps:[
{p:'What should feasible(r) return?',c:[['Whether total required hours at rate r is <= H',1,'That gives a monotonic yes/no predicate.'],['The sorted list of batches',0,'Feasibility should answer one candidate rate.'],['The exact optimal rate recursively',0,'That would defeat the outer binary search.']]},
{p:'What natural lower bound can you usually start with?',c:[['A smallest physically meaningful rate such as 1',1,'Then derive a safe upper bound from constraints.'],['Negative infinity',0,'Rates are positive integers.'],['The number of dictionary keys',0,'That is unrelated.']]},
{p:'Why is the predicate monotonic?',c:[['If r works, any faster rate also works',1,'Increasing processing speed cannot increase required hours.'],['The batches are monotonic',0,'The input itself need not be ordered.'],['Binary search forces it to be',0,'The property must exist before you can use binary search.']]}],h:['Separate “guess r” from “check r.”','Write the yes/no checker first; then ask how its answer changes as r grows.'],model:'“I define feasible(r) by summing the hours needed at rate r. Feasibility changes from false to true once and stays true, so I binary-search for the first feasible integer rate.”',links:[['Koko Eating Bananas','https://leetcode.com/problems/koko-eating-bananas/']]},
{id:'weighted-choice',skill:'dijkstra',scenario:'One path uses 2 edges costing 100 each; another uses 5 edges costing 10 each. You need minimum total cost, not fewest edges.',steps:[
{p:'Why can ordinary breadth-first search choose the wrong route?',c:[['It prioritizes number of edges, not the sum of unequal edge weights',1,'Two expensive edges may cost more than five cheap ones.'],['It cannot traverse graphs',0,'It traverses graphs perfectly well.'],['It requires negative weights',0,'That is unrelated.']]},
{p:'What property allows Dijkstra here?',c:[['All edge weights are nonnegative',1,'Settling the smallest tentative distance is safe under nonnegative weights.'],['Every node has exactly two neighbors',0,'Degree does not make Dijkstra valid.'],['The graph is acyclic',0,'Dijkstra can work with cycles as long as weights are nonnegative.']]},
{p:'If negative edge weights appear, what should you do?',c:[['Do not blindly use standard Dijkstra; reconsider the algorithm',1,'Its greedy settling argument can fail with negative edges.'],['Use the exact same code',0,'That can produce incorrect distances.'],['Convert negatives to zero',0,'That changes the problem.']]}],h:['Contrast “fewest hops” with “lowest accumulated cost.”','Dijkstra is the weighted extension to remember when weights are nonnegative.'],model:'“Because edge costs differ, hop count is not the objective, so BFS is insufficient. With nonnegative weights I use Dijkstra, always expanding the smallest tentative total cost from a min-heap.”',links:[['Network Delay Time','https://leetcode.com/problems/network-delay-time/']]},
{id:'meeting-rooms',skill:'sort',scenario:'Given meeting intervals, determine whether one person can attend all of them without overlap.',steps:[
{p:'What first move makes conflict detection local?',c:[['Sort meetings by start time',1,'Then any conflict must show up between adjacent meetings in that ordering.'],['Compare every pair',0,'It works but wastes O(n²) comparisons.'],['Use Union-Find',0,'This is ordering/overlap, not transitive grouping.']]},
{p:'After sorting, what condition signals a conflict?',c:[['current.start < previous.end',1,'The current meeting begins before the previous one has ended.'],['current.end > previous.end',0,'A later ending time alone does not mean overlap.'],['current.start > 0',0,'Absolute time is irrelevant.']]},
{p:'What dominates runtime?',c:[['Sorting: O(n log n)',1,'The adjacent scan is only O(n).'],['The scan: O(n²)',0,'Each meeting is inspected a constant number of times.'],['Dictionary lookup: O(1)',0,'No dictionary is needed.']]}],h:['Ordering often turns “compare anything with anything” into “compare neighbors.”','Sort by when each interval starts.'],model:'“I sort by start time and scan adjacent meetings. If any meeting starts before the previous one ends, there is an overlap; otherwise the schedule is feasible. Sorting dominates at O(n log n).”',links:[['Merge Intervals','https://leetcode.com/problems/merge-intervals/']]},
{id:'diameter',skill:'trees',scenario:'Find the longest path between any two nodes in a binary tree; the path does not have to pass through the root.',steps:[
{p:'What useful value can each subtree return upward?',c:[['Its height / longest downward path',1,'A parent can combine left and right downward heights into a path through itself.'],['The entire subtree serialized as text',0,'That is far more information than needed.'],['Only whether it is balanced',0,'That does not give path length.']]},
{p:'What candidate path can be evaluated at each node?',c:[['left height + right height',1,'That is the longest path whose highest point is this node.'],['left height only',0,'That ignores a path crossing from left to right.'],['number of children squared',0,'That has no path-length meaning.']]},
{p:'Why keep a separate best-so-far variable?',c:[['The value returned to the parent is height, while the global answer is a different quantity',1,'One recursive contract cannot directly return both without packaging extra state.'],['Recursion cannot return integers',0,'It can.'],['The root always has the diameter',0,'The longest path may lie entirely below the root.']]}],h:['Ask what a parent needs from one child versus what answer you can compute using both children.','Return height; update diameter as a side effect at each node.'],model:'“Each recursive call returns subtree height. At each node I can form a diameter candidate from leftHeight+rightHeight, update the global best, then return 1+max(leftHeight,rightHeight) to the parent.”',links:[['Diameter of Binary Tree','https://leetcode.com/problems/diameter-of-binary-tree/']]},
{id:'stairs',skill:'dp',scenario:'You can climb 1 or 2 steps at a time. Count the ways to reach step n.',steps:[
{p:'What recurrence is hiding here?',c:[['ways(n) = ways(n-1) + ways(n-2)',1,'Every final move came from exactly one or two steps below.'],['ways(n) = n²',0,'There is no reason for a square relationship.'],['ways(n) = ways(n-1) only',0,'That ignores two-step final moves.']]},
{p:'Why is naive recursive branching wasteful?',c:[['It recomputes the same smaller n values many times',1,'The recursion tree contains overlapping subproblems.'],['Python cannot recurse',0,'It can; repeated work is the issue.'],['There are negative edge weights',0,'This is not a shortest-path problem.']]},
{p:'What is the smallest state needed?',c:[['The current step number n',1,'The number of ways from that state depends only on remaining/current position.'],['The full sequence of earlier moves',0,'That history is unnecessary.'],['A set of visited steps',0,'Revisiting a numeric subproblem is exactly what memoization should reuse, not prohibit.']]}],h:['Classify solutions by their last move.','The two smaller questions repeat, so cache them or compute bottom-up.'],model:'“Any path to n ends with a 1-step move from n-1 or a 2-step move from n-2, so ways(n)=ways(n-1)+ways(n-2). Memoization or a two-variable bottom-up loop makes it O(n).”',links:[['Climbing Stairs','https://leetcode.com/problems/climbing-stairs/']]}
);