const SKILLS={hash:'Hash map / set',graphs:'BFS / DFS graphs',union:'Union-Find',heap:'Heap / Top K',topo:'Topological sort',window:'Sliding window',prefix:'Prefix sum + map',binary:'Binary search on answer',dijkstra:'Dijkstra',sort:'Sort + sweep',trees:'Trees / recursion',dp:'Dynamic programming'};
const Q=[
{id:'dedupe',skill:'hash',scenario:'A stream contains millions of listing IDs. Return the first ID that has appeared before.',steps:[
{p:'What is the best first move?',c:[['Compare each ID to all earlier IDs',0,'That repeats linear searching and becomes quadratic.'],['Keep a set of IDs already seen',1,'You only need to answer “have I seen x?” cheaply.'],['Sort the stream after every item',0,'Sorting repeatedly is far more work than a membership lookup.']]},
{p:'What state do you carry?',c:[['A running numeric sum',0,'The actual values seen matter, not their sum.'],['The set of earlier IDs',1,'That is exactly the information each next lookup needs.'],['A queue of the last 10 IDs',0,'A duplicate can be arbitrarily far back.']]},
{p:'What target complexity should you say?',c:[['O(n) expected time, O(n) space',1,'One scan plus expected constant-time set membership.'],['O(n²) time, O(1) space',0,'That is the pairwise brute force.'],['O(log n) total time',0,'You still must inspect the input.']]}],h:['Ask what repeated question you need to make cheap.','The question is literally “has x appeared before?”'],model:'“I will scan once with a set of seen IDs. If the current ID is already present, I return it; otherwise I add it. That is O(n) expected time and O(n) extra space.”',links:[['Contains Duplicate','https://leetcode.com/problems/contains-duplicate/'],['Two Sum','https://leetcode.com/problems/two-sum/']]},
{id:'hops',skill:'graphs',scenario:'Products are nodes; an edge means “directly related.” Find the fewest relationship hops from A to Z. Every edge costs one hop.',steps:[
{p:'Which search should fire first?',c:[['Breadth-first search',1,'Equal-cost edges mean breadth-first layers are distance layers.'],['Depth-first search',0,'It can find a path, but not necessarily the shortest first.'],['Dijkstra',0,'Correct but unnecessary overhead when every edge has the same cost.']]},
{p:'When do you mark a neighbor seen?',c:[['When you enqueue it',1,'That prevents multiple parents from adding duplicates to the queue.'],['Only when you later dequeue it',0,'The same node can enter the queue many times before then.'],['Never; revisiting is useful',0,'Cycles can make that explode or loop forever.']]},
{p:'What is the main edge case?',c:[['A and Z might already be the same node',1,'Then the answer is zero hops.'],['The node labels must be integers',0,'Labels can be anything hashable.'],['The graph must be sorted',0,'Traversal does not require sorted adjacency lists.']]}],h:['Ask whether every move has the same cost.','Explore all nodes one hop away before nodes two hops away.'],model:'“This is an unweighted shortest path, so I would BFS from A. I mark nodes seen when I enqueue them and track distance by level. First discovery of Z gives the minimum hop count.”',links:[['Shortest Path in Binary Matrix','https://leetcode.com/problems/shortest-path-in-binary-matrix/'],['Number of Islands','https://leetcode.com/problems/number-of-islands/']]},
{id:'identity',skill:'union',scenario:'Match signals arrive over time: A=B, D=E, B=C, then C=D. You need fast merge and same-group queries.',steps:[
{p:'Best-fitting data structure?',c:[['Union-Find / Disjoint Set',1,'Repeated union and connectivity queries are its exact job.'],['Heap',0,'A heap tracks priority, not transitive membership.'],['Sliding window',0,'There is no contiguous window here.']]},
{p:'After all four signals, what groups remain?',c:[['{A,B,C} and {D,E}',0,'C=D connects the two groups.'],['{A,B,C,D,E}',1,'Transitive connectivity merges the entire chain.'],['Five separate groups',0,'Every signal merges two components.']]},
{p:'What optimization is worth knowing by name?',c:[['Path compression',1,'It makes repeated find operations extremely cheap.'],['Memoized binary search',0,'That is unrelated.'],['Stable sorting',0,'Ordering is irrelevant to find/union.']]}],h:['Think “which component is x in?” and “merge these components.”','Direct matching is not required; transitivity is the point.'],model:'“I would use Union-Find. Each match unions two representatives; find tells me the current component. Path compression, ideally with union by size/rank, keeps operations near constant amortized time.”',links:[['Accounts Merge','https://leetcode.com/problems/accounts-merge/'],['Redundant Connection','https://leetcode.com/problems/redundant-connection/']]},
{id:'topk',skill:'heap',scenario:'A retrieval system streams 100 million similarity scores. You only need the best 50 candidates.',steps:[
{p:'What should you avoid doing?',c:[['Sorting all 100 million values',1,'It works but spends O(n log n) work and stores everything when K is tiny.'],['Using a size-50 heap',0,'That is the efficient strategy.'],['Discarding candidates that cannot beat the current winners',0,'That is exactly the useful pruning behavior.']]},
{p:'Which heap orientation keeps the 50 largest scores?',c:[['A min-heap of the current winners',1,'The smallest winner is the one to evict when a better score arrives.'],['A max-heap containing all scores',0,'That stores everything and does not solve the memory goal.'],['No ordering at all',0,'You need fast access to the weakest current winner.']]},
{p:'What time complexity is the key comparison?',c:[['O(n log K)',1,'Each stream item can cause a logarithmic operation on a heap of size K.'],['O(n log n)',0,'That is the sort-everything approach.'],['O(K log n)',0,'You still inspect all n candidates.']]}],h:['You do not care about the ordering of the losers.','Keep only K winners and make the weakest winner easy to remove.'],model:'“I will maintain a min-heap of at most K scores. For each candidate I push it, then pop if the heap exceeds K. That keeps the best K seen so far in O(n log K) time and O(K) space.”',links:[['Top K Frequent Elements','https://leetcode.com/problems/top-k-frequent-elements/'],['K Closest Points','https://leetcode.com/problems/k-closest-points-to-origin/']]},
{id:'deps',skill:'topo',scenario:'A pipeline has prerequisites: normalize before embed, embed before rank, and validate before publish. Return a valid execution order or report a cycle.',steps:[
{p:'What pattern is this?',c:[['Topological sorting',1,'The problem is ordering a directed dependency graph.'],['Binary search',0,'There is no monotonic numeric boundary.'],['Union-Find',0,'Connectivity does not give a valid dependency order.']]},
{p:'What does the queue contain in Kahn’s algorithm?',c:[['Nodes with zero unmet prerequisites',1,'Those are safe to execute now.'],['The highest-scoring nodes',0,'Priority is not the constraint.'],['Every node in arbitrary order',0,'That can violate prerequisites.']]},
{p:'How do you detect a cycle?',c:[['Fewer than n nodes are processed',1,'A cyclic remainder never reaches indegree zero.'],['The queue is ever larger than one',0,'Multiple valid choices are fine.'],['Any node has two prerequisites',0,'Multiple prerequisites are normal.']]}],h:['Ask what can legally happen right now.','Track each node’s count of unmet incoming dependencies.'],model:'“I will build indegrees and an adjacency list, enqueue all zero-indegree nodes, and repeatedly remove one while decrementing its dependents. If I process fewer than n nodes, a cycle prevents a valid order.”',links:[['Course Schedule','https://leetcode.com/problems/course-schedule/'],['Course Schedule II','https://leetcode.com/problems/course-schedule-ii/']]},
{id:'unique-window',skill:'window',scenario:'Given a sequence of category IDs, find the longest contiguous stretch containing no repeated category.',steps:[
{p:'What pattern fits the word “contiguous” plus a local validity rule?',c:[['Sliding window',1,'You can expand right and shrink left until the window is valid again.'],['Union-Find',0,'Connectivity groups are unrelated to contiguous ranges.'],['Topological sort',0,'There are no dependencies.']]},
{p:'What invariant should the current window maintain?',c:[['No category appears twice',1,'The window should be valid after every shrink.'],['The window is always length K',0,'K is not fixed here.'],['The values are sorted',0,'Sorting would destroy contiguity.']]},
{p:'When a duplicate arrives, what moves?',c:[['Move the left boundary until the duplicate conflict is gone',1,'Keep the right boundary at the new item and restore validity.'],['Restart from scratch at the duplicate',0,'That throws away useful overlap and can miss longer windows.'],['Sort the current window',0,'Again, sorting destroys the original positions.']]}],h:['Maintain one contiguous region rather than recomputing each substring.','Expand right; only move left when the rule is violated.'],model:'“I will keep a sliding window and a set or last-seen map. I expand right; when the new value creates a duplicate, I advance left until the window is unique again. Each index moves at most once or twice, so it is O(n).”',links:[['Longest Substring Without Repeating Characters','https://leetcode.com/problems/longest-substring-without-repeating-characters/']]},
{id:'subarray-sum',skill:'prefix',scenario:'An array contains positive and negative adjustments. Count contiguous subarrays whose sum equals target K.',steps:[
{p:'Why is a normal shrinking sliding window unsafe?',c:[['Negative values destroy the monotonic “too large → shrink” rule',1,'Removing a negative can increase the sum, so the usual direction logic breaks.'],['Arrays cannot be used with two pointers',0,'They can; the issue is the value behavior.'],['K may be zero',0,'Zero alone does not break sliding windows.']]},
{p:'What should you remember while scanning?',c:[['Counts of prefix sums seen so far',1,'Current prefix minus an earlier prefix gives a subarray sum.'],['Only the maximum value',0,'That does not encode interval sums.'],['A heap of all values',0,'Priority ordering does not help count exact subarray sums.']]},
{p:'Which lookup finds subarrays ending here with sum K?',c:[['prefix - K',1,'If oldPrefix = currentPrefix-K, their difference is K.'],['prefix + K',0,'That would make the difference negative K.'],['K / prefix',0,'Subarray sums use subtraction of cumulative totals.']]}],h:['Write currentPrefix - oldPrefix = K.','Rearrange: oldPrefix = currentPrefix - K, then count how often that old prefix occurred.'],model:'“I keep a running prefix sum and a frequency map initialized with {0:1}. At each position, the number of valid subarrays ending here is freq[prefix-K], then I increment freq[prefix]. That is O(n) time.”',links:[['Subarray Sum Equals K','https://leetcode.com/problems/subarray-sum-equals-k/']]},
{id:'capacity',skill:'binary',scenario:'Find the smallest batch capacity that lets all jobs finish within D days. If capacity X works, any larger capacity also works.',steps:[
{p:'What structure matters most?',c:[['A monotonic false→true feasibility boundary',1,'That is what lets you discard half the candidate capacities each time.'],['A graph cycle',0,'The problem is a numeric threshold.'],['Duplicate detection',0,'There is no repeated-value lookup.']]},
{p:'What do you binary-search?',c:[['The answer space of possible capacities',1,'Binary search is not limited to finding a value already in an array.'],['The jobs in their original order',0,'The index of a job is not the unknown threshold.'],['Only powers of two',0,'Any integer candidate in the bounded range can be tested.']]},
{p:'If mid works and you want the minimum working value, what happens?',c:[['Move the upper bound down to mid',1,'A smaller working answer may still exist.'],['Move the lower bound above mid',0,'That discards potentially better working values.'],['Stop immediately',0,'Mid may work without being minimal.']]}],h:['Imagine writing feasible(x) that returns only true or false.','If feasible results look F F F T T T, find the first T.'],model:'“I will binary-search capacity, using a linear feasibility check for whether that capacity finishes within D days. Because feasibility is monotonic, I can find the smallest working capacity in O(n log range).”',links:[['Capacity To Ship Packages Within D Days','https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/'],['Koko Eating Bananas','https://leetcode.com/problems/koko-eating-bananas/']]},
{id:'weighted',skill:'dijkstra',scenario:'Edges between services have different nonnegative latencies. Find the minimum total latency from source to every service.',steps:[
{p:'Which shortest-path algorithm now fits?',c:[['Dijkstra with a min-heap',1,'Weights differ, but they are nonnegative.'],['Plain BFS',0,'BFS minimizes edge count, not weighted cost.'],['Depth-first search',0,'DFS does not settle shortest weighted distances.']]},
{p:'What does the heap prioritize?',c:[['Smallest known total distance so far',1,'Dijkstra repeatedly expands the cheapest unsettled candidate.'],['Largest edge weight',0,'A single edge does not determine path cost.'],['Alphabetical node name',0,'Names carry no shortest-path meaning.']]},
{p:'Python heaps do not decrease-key cleanly. What is the common trick?',c:[['Push the improved distance again and skip stale pops later',1,'Duplicate heap entries are fine if stale ones are ignored.'],['Mutate arbitrary heap elements in place',0,'That can violate the heap invariant unless reheapified carefully.'],['Restart the whole algorithm after every improvement',0,'That is unnecessary.']]}],h:['BFS works only when every move costs the same.','Always expand the currently cheapest known route; nonnegative weights make that safe.'],model:'“I will use Dijkstra: distances start at infinity except the source, and a min-heap stores (distance,node). On relaxation I push improved distances; when I pop a stale entry, I skip it. Complexity is O((V+E) log V) in the usual adjacency-list implementation.”',links:[['Network Delay Time','https://leetcode.com/problems/network-delay-time/']]},
{id:'intervals',skill:'sort',scenario:'You have unsorted time intervals representing duplicate-processing windows. Merge every overlapping interval.',steps:[
{p:'What move makes the global overlap problem local?',c:[['Sort intervals by start time',1,'Then only the current merged interval needs comparison with the next.'],['Hash every endpoint',0,'Endpoint membership does not reveal overlap structure.'],['Run BFS over times',0,'This is not naturally a graph traversal problem.']]},
{p:'After sorting, when do you extend the current interval?',c:[['When next.start <= current.end',1,'That means they overlap or touch under the usual inclusive interpretation.'],['Whenever next.end is larger',0,'A later interval can have a larger end without overlapping.'],['Only when starts are equal',0,'Overlaps can begin at different positions.']]},
{p:'What complexity dominates?',c:[['O(n log n) from sorting',1,'The merge scan itself is linear.'],['O(n²) from checking every pair',0,'Sorting avoids that.'],['O(log n) total',0,'You must at least read all intervals.']]}],h:['Ask whether ordering the input makes only neighboring items relevant.','Sort by start, then carry one current merged interval.'],model:'“I sort by start time, then scan. If the next interval begins before the current one ends, I extend the end; otherwise I emit the current interval and start a new one. Sorting dominates at O(n log n).”',links:[['Merge Intervals','https://leetcode.com/problems/merge-intervals/']]},
{id:'bst',skill:'trees',scenario:'Given a binary tree, determine whether it is a valid binary search tree: every value in a left subtree must be smaller, every value in a right subtree larger.',steps:[
{p:'What is the subtle trap?',c:[['Checking only each node against its immediate children',1,'A deeper descendant can violate an ancestor’s constraint.'],['Recursion is forbidden',0,'Recursion is a natural solution here.'],['The tree must be balanced',0,'Balance is irrelevant to BST validity.']]},
{p:'What information should recursion pass downward?',c:[['The allowed lower and upper bounds',1,'Ancestor constraints must follow every descendant.'],['Only the parent value',0,'One parent value is insufficient for all ancestor constraints.'],['The current depth only',0,'Depth does not determine value validity.']]},
{p:'What does a null child mean?',c:[['Valid base case',1,'An empty subtree violates nothing.'],['Automatic failure',0,'Leaves would never validate.'],['Restart from the root',0,'There is nothing to inspect.']]}],h:['A node can be valid relative to its parent but invalid relative to its grandparent.','Carry the entire allowed numeric range downward.'],model:'“I recursively validate each node against a (low, high) range. The left child inherits (low,node.val); the right inherits (node.val,high). A null subtree is valid. This visits each node once.”',links:[['Validate Binary Search Tree','https://leetcode.com/problems/validate-binary-search-tree/']]},
{id:'coins',skill:'dp',scenario:'You need the minimum number of allowed coin values to make amount A. The same remaining amounts appear again and again in different choice paths.',steps:[
{p:'What clue suggests dynamic programming?',c:[['Repeated overlapping subproblems',1,'Different choice paths ask for the same smaller amount repeatedly.'],['The input happens to be a list',0,'Lists alone do not imply DP.'],['There is a graph somewhere conceptually',0,'Many problems can be drawn as graphs; the useful clue is repeated state.']]},
{p:'What is a natural state?',c:[['Best answer for a remaining amount',1,'The remaining amount fully identifies the repeated subproblem.'],['The entire history of coin picks',0,'That carries much more information than needed.'],['Only the largest coin',0,'The optimum can depend on all denominations.']]},
{p:'What does memoization buy you?',c:[['Solve each distinct remaining amount once',1,'Cached answers prevent exponential recomputation.'],['It sorts the coins automatically',0,'Caching and sorting are different ideas.'],['It guarantees a greedy choice is optimal',0,'Coin Change is a classic case where greedy can fail.']]}],h:['Ask: if I branch on choices, do I encounter the same smaller question repeatedly?','Define solve(remaining) and cache it.'],model:'“I define the subproblem as the minimum coins needed for a remaining amount. For each coin I try solve(remaining-coin), and memoize by remaining amount so each state is solved once. Then I can discuss a bottom-up table if preferred.”',links:[['Coin Change','https://leetcode.com/problems/coin-change/']]}
];
const KEY='amazon-skill-stats';
let stats=JSON.parse(localStorage.getItem(KEY)||'{}');
let mode='sprint',session=[],qi=0,si=0,sessionCorrect=0,sessionAnswered=0,locked=false;
const $=id=>document.getElementById(id);
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function accuracy(skill){const s=stats[skill];return !s||!s.attempts?null:s.correct/s.attempts}
function record(skill,correct){const s=stats[skill]||(stats[skill]={attempts:0,correct:0});s.attempts++;if(correct)s.correct++;localStorage.setItem(KEY,JSON.stringify(stats));renderMastery();renderWeak()}
function pick(){if(mode==='sprint')return shuffle(Q).slice(0,10);if(mode==='all')return shuffle(Q);return [...Q].sort((a,b)=>{const aa=accuracy(a.skill),bb=accuracy(b.skill);return (aa===null ? .55 : aa)-(bb===null ? .55 : bb)})}
function start(){session=pick();qi=0;si=0;sessionCorrect=0;sessionAnswered=0;locked=false;renderQuestion();updateScore()}
function updateScore(){const pct=sessionAnswered?Math.round(100*sessionCorrect/sessionAnswered):0;$('scoreText').textContent=sessionAnswered?`${sessionCorrect}/${sessionAnswered} decisions correct`:'Ready';$('scoreSub').textContent=sessionAnswered?`${pct}% this session · mistakes drive weak-topic review`:'Recognition matters more than typing speed here.';$('sessionProgress').textContent=session.length?`${Math.min(qi+1,session.length)}/${session.length}`:'0/0'}
function esc(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function renderQuestion(){if(qi>=session.length){renderEnd();return}const q=session[qi],st=q.steps[si];locked=false;$('trainer').innerHTML=`<article class="questionCard"><div class="qTop"><span class="qNum">Problem ${qi+1} of ${session.length} · decision ${si+1} of ${q.steps.length}</span><span id="patternTag" class="patternReveal hiddenAnswer">${SKILLS[q.skill]}</span></div><h2>${esc(q.scenario)}</h2><div class="stage"><div class="stagePrompt">${esc(st.p)}</div><div id="choices">${st.c.map((x,i)=>`<button class="choice" data-i="${i}">${esc(x[0])}</button>`).join('')}</div><div id="stageFeedback" class="stageFeedback"></div></div><div class="continueRow"><button class="btn small" id="hintBtn">Hint</button><button class="btn primary" id="continueBtn" hidden>${si+1<q.steps.length?'Next decision':'See explanation'}</button></div><div id="hintBox"></div></article>`;document.querySelectorAll('#choices .choice').forEach(b=>b.onclick=()=>answer(+b.dataset.i));$('hintBtn').onclick=showHint;$('continueBtn').onclick=advance;updateScore()}
function answer(i){if(locked)return;locked=true;const q=session[qi],st=q.steps[si],choice=st.c[i],correct=choice[1]===1;sessionAnswered++;if(correct)sessionCorrect++;record(q.skill,correct);const buttons=[...document.querySelectorAll('#choices .choice')];buttons.forEach((b,j)=>{b.disabled=true;if(st.c[j][1]===1)b.classList.add('correct')});buttons[i].classList.add(correct?'correct':'wrong');$('stageFeedback').innerHTML=`<b>${correct?'Yes.':'Not quite.'}</b> ${esc(choice[2])}`;$('patternTag').classList.remove('hiddenAnswer');$('continueBtn').hidden=false;updateScore()}
function showHint(){const q=session[qi],box=$('hintBox'),shown=box.children.length;const hint=q.h[Math.min(shown,q.h.length-1)];if(!hint)return;const d=document.createElement('div');d.className='hint show';d.textContent=`Hint ${shown+1}: ${hint}`;box.appendChild(d);if(shown+1>=q.h.length)$('hintBtn').disabled=true}
function advance(){const q=session[qi];if(si+1<q.steps.length){si++;renderQuestion();return}showExplanation(q)}
function showExplanation(q){const links=q.links.map(x=>`<a class="btn small" target="_blank" href="${x[1]}">${x[0]}</a>`).join('');$('trainer').innerHTML=`<article class="questionCard"><div class="qTop"><span class="qNum">Problem ${qi+1} complete</span><span class="patternReveal">${SKILLS[q.skill]}</span></div><h2>${esc(q.scenario)}</h2><div class="revealBox"><h3>Model interview answer</h3><p>${esc(q.model)}</p><div class="actions"><a class="btn small" href="index.html?review=${q.skill}">Review this lesson</a>${links}</div></div><div class="continueRow"><button class="btn primary" id="nextQ">Next problem</button></div></article>`;$('nextQ').onclick=()=>{qi++;si=0;renderQuestion()}}
function renderEnd(){const pct=sessionAnswered?Math.round(100*sessionCorrect/sessionAnswered):0;$('trainer').innerHTML=`<div class="endCard"><h2>Session complete · ${pct}% of decisions correct</h2><p>This score is diagnostic, not a grade. Use <b>Weak topics</b> next; the course will front-load the patterns where your reasoning was least reliable.</p><div class="actions"><button class="btn primary" id="again">Run another session</button><button class="btn" id="weakNow">Practice weak topics</button></div></div>`;$('again').onclick=start;$('weakNow').onclick=()=>{setMode('weak');start()};$('sessionProgress').textContent=`${session.length}/${session.length}`}
function renderMastery(){const el=$('mastery');el.innerHTML=Object.entries(SKILLS).map(([k,n])=>{const a=accuracy(k);const cls=a===null?'':a>=.8?'good':a<.6?'weak':'';const txt=a===null?'new':`${Math.round(a*100)}%`;return `<span class="skillChip ${cls}">${n} · ${txt}</span>`}).join('')}
function renderWeak(){const rows=Object.entries(SKILLS).map(([k,n])=>({k,n,a:accuracy(k),s:stats[k]})).sort((x,y)=>(x.a===null ? .55 : x.a)-(y.a===null ? .55 : y.a));$('weakList').innerHTML=rows.map(x=>{const p=x.a===null?0:Math.round(100*x.a);const label=x.a===null?'not tested':`${p}% · ${x.s.attempts} decisions`;return `<div class="weakRow"><div><a href="index.html?review=${x.k}">${x.n}</a><div class="meter"><span style="width:${p}%"></span></div></div><span class="tiny">${label}</span></div>`}).join('')}
function setMode(m){mode=m;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('startBtn').textContent=m==='sprint'?'Start 10-question sprint':m==='weak'?'Start weak-topic session':'Start all patterns'}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('startBtn').onclick=start;$('restartBtn').onclick=start;renderMastery();renderWeak();setMode('sprint');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});